on:
  pull_request:
    branches:
    - release/*
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Patchable.sln'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

#    - name: Setup NuGet
#      uses: NuGet/setup-nuget@v1.0.5

 #   - name: Restore dependencies
 #     run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

 #   - name: Install dependencies
 #     run: dotnet restore
 #   - name: Build
 #     run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release 

    - name: Publish
      run: dotnet nuget push **\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json